from pyspark.sql import SparkSession
from pyspark.sql.functions import col, max as spark_max
spark = SparkSession.builder.master("local[2]").appName("SubjectLevelDataPreparation").config("spark.sql.shuffle.partitions", "64").getOrCreate()
BASE = "hdfs://localhost:9000/user/mahith/icu"
INPUT = f"{BASE}/processed/window_dataset.parquet"
TRAIN_OUTPUT = f"{BASE}/train"
VALIDATION_OUTPUT = f"{BASE}/validation"
TEST_OUTPUT = f"{BASE}/test"
SEED = 42
try:
    print("SUBJECT-LEVEL DATA PREPARATION")
    print("\nLOADING WINDOW DATASET")
    df = spark.read.parquet(INPUT)
    total_rows = df.count()
    total_subjects = df.select("subject_id").distinct().count()
    total_stays = df.select("stay_id").distinct().count()
    null_subjects = df.filter(col("subject_id").isNull()).count()
    print(f"Total rows: {total_rows:,}")
    print(f"Total subjects: {total_subjects:,}")
    print(f"Total stays: {total_stays:,}")
    print(f"Null subject_id rows: {null_subjects:,}")
    print("\nCREATING SUBJECT-LEVEL LABELS")
    subject_labels = df.groupBy("subject_id").agg(spark_max("mortality").alias("subject_label"))
    print("\nSUBJECT LABEL DISTRIBUTION")
    subject_labels.groupBy("subject_label").count().orderBy("subject_label").show()
    positive_subjects = subject_labels.filter(col("subject_label") == 1)
    negative_subjects = subject_labels.filter(col("subject_label") == 0)
    positive_count = positive_subjects.count()
    negative_count = negative_subjects.count()
    print(f"Positive subjects: {positive_count:,}")
    print(f"Negative subjects: {negative_count:,}")
    print("\nSUBJECT-LEVEL SPLIT")
    positive_split = positive_subjects.randomSplit([0.70, 0.15, 0.15], seed=SEED)
    negative_split = negative_subjects.randomSplit([0.70, 0.15, 0.15], seed=SEED)
    train_subjects = positive_split[0].unionByName(negative_split[0]).cache()
    validation_subjects = positive_split[1].unionByName(negative_split[1]).cache()
    test_subjects = positive_split[2].unionByName(negative_split[2]).cache()
    train_subject_count = train_subjects.count()
    validation_subject_count = validation_subjects.count()
    test_subject_count = test_subjects.count()
    print(f"Train subjects: {train_subject_count:,}")
    print(f"Validation subjects: {validation_subject_count:,}")
    print(f"Test subjects: {test_subject_count:,}")
    print("\nCREATING WINDOW-LEVEL SPLITS")
    train = df.join(train_subjects.select("subject_id"), "subject_id", "inner")
    validation = df.join(validation_subjects.select("subject_id"), "subject_id", "inner")
    test = df.join(test_subjects.select("subject_id"), "subject_id", "inner")
    train_rows = train.count()
    validation_rows = validation.count()
    test_rows = test.count()
    print(f"Train rows: {train_rows:,}")
    print(f"Validation rows: {validation_rows:,}")
    print(f"Test rows: {test_rows:,}")
    print("\nVERIFYING SUBJECT OVERLAP")
    train_subject_check = train.select("subject_id").distinct()
    validation_subject_check = validation.select("subject_id").distinct()
    test_subject_check = test.select("subject_id").distinct()
    train_validation_overlap = train_subject_check.join(validation_subject_check, "subject_id", "inner").count()
    train_test_overlap = train_subject_check.join(test_subject_check, "subject_id", "inner").count()
    validation_test_overlap = validation_subject_check.join(test_subject_check, "subject_id", "inner").count()
    print(f"Train Validation subject overlap: {train_validation_overlap}")
    print(f"Train Test subject overlap: {train_test_overlap}")
    print(f"Validation Test subject overlap: {validation_test_overlap}")
    print("\nVERIFYING STAY OVERLAP")
    train_stays = train.select("stay_id").distinct()
    validation_stays = validation.select("stay_id").distinct()
    test_stays = test.select("stay_id").distinct()
    train_validation_stay_overlap = train_stays.join(validation_stays, "stay_id", "inner").count()
    train_test_stay_overlap = train_stays.join(test_stays, "stay_id", "inner").count()
    validation_test_stay_overlap = validation_stays.join(test_stays, "stay_id", "inner").count()
    print(f"Train Validation stay overlap: {train_validation_stay_overlap}")
    print(f"Train Test stay overlap: {train_test_stay_overlap}")
    print(f"Validation Test stay overlap: {validation_test_stay_overlap}")
    print("\nVERIFYING ROW CONSERVATION")
    split_total_rows = train_rows + validation_rows + test_rows
    row_conservation = split_total_rows == total_rows
    print(f"Original rows: {total_rows:,}")
    print(f"Split rows: {split_total_rows:,}")
    print(f"Row conservation: {'PASS' if row_conservation else 'FAIL'}")
    print("\nVERIFYING SUBJECT CONSERVATION")
    split_total_subjects = train_subject_count + validation_subject_count + test_subject_count
    subject_conservation = split_total_subjects == total_subjects
    print(f"Original subjects: {total_subjects:,}")
    print(f"Split subjects: {split_total_subjects:,}")
    print(f"Subject conservation: {'PASS' if subject_conservation else 'FAIL'}")
    print("\nLABEL DISTRIBUTION")
    for name, split in [("TRAIN", train), ("VALIDATION", validation), ("TEST", test)]:
        print(f"\n{name}")
        split.groupBy("mortality").count().orderBy("mortality").show()
    split_ok = null_subjects == 0 and row_conservation and subject_conservation and train_validation_overlap == 0 and train_test_overlap == 0 and validation_test_overlap == 0 and train_validation_stay_overlap == 0 and train_test_stay_overlap == 0 and validation_test_stay_overlap == 0
    if split_ok:
        print("\nWRITING SPLITS")
        train.write.mode("overwrite").parquet(TRAIN_OUTPUT)
        validation.write.mode("overwrite").parquet(VALIDATION_OUTPUT)
        test.write.mode("overwrite").parquet(TEST_OUTPUT)
        print("SPLITS WRITTEN SUCCESSFULLY")
        print("\nFINAL RESULT: SUBJECT-LEVEL SPLIT PASSED")
        print("SAFE TO REGENERATE CLEAN FEATURES")
    else:
        print("\nSPLIT VERIFICATION FAILED - NOT WRITING")
        print("\nFINAL RESULT: SUBJECT-LEVEL SPLIT FAILED")
        print("DO NOT PROCEED")
    train_subjects.unpersist()
    validation_subjects.unpersist()
    test_subjects.unpersist()
finally:
    spark.stop()